### PR TITLE
added changes to add server endpoint

### PR DESCRIPTION
**Pull request by SarthakJain26**
This PR will add serverEndpoint in the litmusconfig file which can be configured as per the development setup. serverEndpoint is the endpoint where graphql server is running.

``` accounts:
- users:
  - expires_in: "1697525696"
    token: <jwt_token>
    username: admin
  endpoint: http://localhost:3000
  serverEndpoint: http://localhost:8080
apiVersion: v1
current-account: http://localhost:3000
current-user: admin
kind: Config 
```

### CODE REVIEW

**Review by Saranya-jena — APPROVED** [review]

**Comment by Saranya-jena** [comment]
LGTM 🚀

**Comment by Nageshbansal** [comment]
Lgtm ✅

**Review by gdsoumya — COMMENTED** [review]
ServerEndpoint should be an optional thing and not something we should push to production configs as this is specifically for development. It's confusing to have multiple endpoints in the config, so I would suggest to not persist server endpoint in the config by default but during development one can add the field and the code should be considering `serverEndpoint != "" ? serverEndpoint : endpoint`

**Comment by imrajdas** [comment]
can we rename this to authEndpoint and ServerEndpoint?

**Comment by SarthakJain26** [comment]
> ServerEndpoint should be an optional thing and not something we should push to production configs as this is specifically for development. It's confusing to have multiple endpoints in the config, so I would suggest to not persist server endpoint in the config by default but during development one can add the field and the code should be considering `serverEndpoint != "" ? serverEndpoint : endpoint`

serverEndpoint is not something that users will have to worry about. It will be set same as the endpoint while configuring litmusctl. Only for the developers who want to update the server endpoint can update the it in the config.

**Comment by SarthakJain26** [comment]
> can we rename this to authEndpoint and ServerEndpoint?

Renaming endpoint to authEndpoint will make the litmusconfig not backward compatible, that's why it has been kept the same.

**Review by Jonsy13 — APPROVED** [review]

**Pull request merged**
