### PR TITLE
added ability to use custom cert in cli

### PR DESCRIPTION
**Pull request by gdsoumya**
This PR adds :
1. Ability to use custom cert in cli
2. Separates skipSSL for cli and agent

**NOTE:** `--skipSSL` is now only for cli, to configure agent to skip SSL check either set it during agent creation (interactive mode) or use `--skip-agent-ssl` for non-interactive mode

### CODE REVIEW

**Review by rajdas98 — CHANGES_REQUESTED** [review]
You can raise this PR to master. master and v0.7.0 branches are synced.

@Jonsy13 can confirm that.

**Comment by gdsoumya** [comment]
> You can raise this PR to master. master and v0.7.0 branches are synced.
> 
> @Jonsy13 can confirm that.

I think @Jonsy13 mentioned some testing that's needed for v0.7.0 before it can be merged to master, it is not in sync yet I believe.

**Comment by rajdas98** [comment]
0.7.0 can't be rebuilt so, no benefit of pushing there. I created the 0.7.0 branch from the master. I think commits are synced.

**Comment by gdsoumya** [comment]
Updated branch

**Review by rajdas98 — APPROVED** [review]

**Comment by rajdas98** [comment]
@Jonsy13 can you review this?

**Review by Jonsy13 — APPROVED** [review]

**Pull request merged**
