### PR TITLE
fix : output flag for get projects 

### LINKED ISSUE #192: --output=json does not print json format
Hi. When I try to get the project id in json or yaml format, the output is the interactive table, not json

```
$ litmusctl get projects --output=json
$ litmusctl get projects --output json
$ litmusctl get projects -o=json
$ litmusctl get projects -o json
```

```
PROJECT ID                                      PROJECT NAME            CREATED AT
1234567-89ab-cdef-12345-6789abcdefab            admin-project           123-45-67 89:01:23 +0000 UTC
✔ Press Enter to show the next page (or type 'q' to quit): █
```

How can I print json format? I tried with litmusctl 1.1.0 and 1.2.0.

What I'm trying to do is to automate the creation of a chaos-environment with litmusctl, but it asks for a project-id first. 
```
$ litmusctl create chaos-environment --name=my-environment --type=cluster --project-id=XXXXX
```

### PR DESCRIPTION
**Pull request by shivam-Purohit**
closes #192

fixed the output flag for the get projects which was not getting recognized in the code.

### CODE REVIEW

**Comment by shivam-Purohit** [comment]
@neelanjan00 @SarthakJain26 do I also add a prompt for scanning format if null?

**Comment by SarthakJain26** [comment]
> @neelanjan00 @SarthakJain26 do I also add a prompt for scanning format if null?

Not needed @shivam-Purohit , since we already have logic for handling the `""` case, or the default case

**Comment by SarthakJain26** [comment]
@shivam-Purohit please fix the build pipeline

**Review by neelanjan00 — APPROVED** [review]

**Comment by shivam-Purohit** [comment]
> @shivam-Purohit please fix the build pipeline

fixed!

**Review by SarthakJain26 — APPROVED** [review]

**Pull request merged**
